### ISSUE TITLE
Miscurled single quotes

### ISSUE THREAD

**Issue by drgrigg** [PiperKev/rafael-sabatini_the-sea-hawk#1]
There are a bunch of incorrectly curled single quotes in Chapter 2-4 and maybe elsewhere. Examples:

```
<p>“At that,” he writes, “I thrust myself between to shield her. ’Thou dog,’ I cried, ’thou shalt be made to suffer!’</p>
			<p>“ ’Suffer?’ quoth he, and mocked me with his deep laugh. ’I have suffered already. ’Tis for that reason I am here.’</p>
```

Basically anywhere there is speech quoted within speech this error comes up.

I used this regex to find them : `[ ]’[A-Za-z]` 

There are a great many **correct** usages, mainly `’tis` and `’Twas` etc, that you'll have to ignore.

**Comment by PiperKev** [comment]
Fixed.
