### ISSUE TITLE
Long description issues

### ISSUE THREAD

**Issue by drgrigg** [PiperKev/rafael-sabatini_the-sea-hawk#2]
Firstly, there's a typo: fued -> feud .

I feel the first paragraph is a bit of a chunk of exposition which could maybe be cut down a little. Particularly at the beginning it's a bit 'fine-grained' in detail. 

Certainly I would break this first paragraph up into two or three paragraphs.  Maybe break at "When Lionel..." and "For six months"?

I also think there's too much biographical detail about Rafael Sabatini. Bear in mind that, as you point out, he wrote many books, and we don't want to repeat a detailed biography on each one as we publish them. Really just the first and last two sentences would do here.

**Comment by drgrigg** [comment]
You could also mention at the end that the book was twice turned into a film, including a famous one with Errol Flynn.

**Comment by PiperKev** [comment]
Tweaked long description.

**Comment by drgrigg** [comment]
A few minor tweaks to your long description tweak!

- Needs a period at the end of the first paragraph
- The 'A' in 'A Cornish gentleman' should be lower case
- I would add "his" before "jealous half-brother"
- and I would start a new paragraph for the bit about the movies.
